// Original markup from claude.ai/code (ChatContextRing), class strings unchanged.
// Only the "Kontextfenster" section is dropped. build-css.mjs reads every class="" below.
/* classes: cds-root bg-fill-accent bg-fill-warning bg-fill-danger */
(() => {
  const BUTTON = `<button type="button" data-cds="Button" data-cds-icon-only="" data-cds-ghost="" class="cds-reset group/btn relative isolate inline-flex items-center justify-center gap-1.5 whitespace-nowrap select-none cursor-[var(--cds-cursor-interactive)] aria-disabled:cursor-default data-[disabled]:cursor-default border-0 outline-none focus-visible:outline-hidden [&[data-initial-focus]:focus]:outline-hidden rounded h-control font-sans text-body [&:disabled:not([aria-busy])]:opacity-disabled disabled:pointer-events-none transition-shadow duration-fast text-primary font-normal aria-pressed:text-accent focus-visible:shadow-focus [&[data-initial-focus]:focus]:shadow-focus aspect-square w-control px-0 shrink-0" aria-haspopup="dialog" aria-expanded="false" data-testid="chat-context-ring"><span aria-hidden="true" class="absolute -z-[1] rounded-[inherit] inset-0 cds-btn-squish"><span data-cds-part="paint" class="absolute inset-0 rounded-[inherit] transition-[background-color,box-shadow,color] duration-fast ease-out group-focus-visible/btn:shadow-[inset_0_0_0_1px_var(--cds-page-bg)] group-[[data-initial-focus]:focus]/btn:shadow-[inset_0_0_0_1px_var(--cds-page-bg)] bg-transparent group-hover/btn:bg-fill-ghost-hover group-[[aria-haspopup][aria-expanded=true]]/btn:bg-fill-ghost-hover group-aria-pressed/btn:bg-accent group-hover/btn:group-aria-pressed/btn:bg-accent "></span></span><span class="inline-flex min-w-0 items-center gap-1 "><svg width="12" height="12" viewBox="0 0 12 12" class="-rotate-90" aria-hidden="true"><circle cx="6" cy="6" r="5" fill="none" stroke-width="2" stroke="var(--cds-alpha-2)"></circle><circle data-slot="ring" cx="6" cy="6" r="5" fill="none" stroke-width="2" stroke-dasharray="31.41592653589793" stroke-dashoffset="31.41592653589793" stroke-linecap="round" stroke="var(--cds-fill-accent)" class="transition-[stroke-dashoffset] duration-300"></circle></svg></span></button>`;

  const POPUP = `<div data-cds="Popover" data-cds-overlay="" role="dialog" tabindex="-1" class="draggable-none rounded-card bg-surface-3 shadow-panel cds-reset text-body font-normal text-primary outline-none focus-visible:outline-hidden epitaxy-root break-words w-[360px] max-w-[calc(100vw-2rem)] max-h-[min(var(--available-height),640px)]"><div tabindex="-1" data-cds-popover-body="" data-cds-sheet-scroll="" class="[display:inherit] [flex-direction:inherit] [flex-wrap:inherit] [align-items:inherit] [justify-content:inherit] [justify-items:inherit] [gap:inherit] [grid-template-columns:inherit] [grid-template-rows:inherit] [grid-auto-flow:inherit] [grid-auto-columns:inherit] [grid-auto-rows:inherit] col-span-full row-span-full self-stretch justify-self-stretch max-h-[inherit] min-h-0 min-w-0 flex-auto overflow-y-auto rounded-[inherit] outline-none focus-visible:outline-hidden scroll-fade-y p-0"><h2 data-slot="sr-title" class="sr-only"></h2><div class="flex flex-col py-sm"><div class="flex flex-col gap-xs"><div class="flex items-center justify-between gap-2 px-lg py-xs min-h-[20px]"><span data-slot="heading" class="text-footnote text-muted"></span><a data-slot="settings-link" href="/settings/usage" class="df-link-card p-xs -m-pad-xs text-muted hover:text-primary"><span data-cds="Icon" style="font-size: calc(0.75rem * var(--cds-rem-scale, 1)); font-weight: 577.8;" aria-hidden="true"></span></a></div><div data-slot="rows" class="flex flex-col gap-sm px-lg pb-xs"></div></div></div></div></div>`;

  // one window row (z in the original bundle)
  const ROW = `<div class="flex flex-col"><div class="flex items-baseline justify-between gap-2"><span data-slot="label" class="text-footnote text-primary truncate"></span><span class="flex items-baseline gap-1.5 text-footnote text-muted tabular-nums shrink-0"><span data-slot="reset"></span><span data-slot="pct"></span></span></div><div class="mt-pad-xs h-[4px] rounded-[3px] overflow-hidden bg-alpha-1" role="progressbar" aria-valuemin="0" aria-valuemax="100"><div data-slot="bar" class="h-full bg-fill-accent transition-[width]"></div></div></div>`;

  // extra-usage row (R in the original bundle): no reset text, optional bar
  const EXTRA = `<div class="flex flex-col"><div class="flex items-baseline justify-between gap-2"><span data-slot="label" class="text-footnote text-primary truncate"></span><span data-slot="value" class="text-footnote text-muted tabular-nums shrink-0"></span></div><div data-slot="track" class="mt-pad-xs h-[4px] rounded-[3px] overflow-hidden bg-alpha-1" role="progressbar" aria-valuemin="0" aria-valuemax="100"><div data-slot="bar" class="h-full bg-fill-accent transition-[width]"></div></div></div>`;

  globalThis.__CUR_MARKUP = { BUTTON, POPUP, ROW, EXTRA };
})();
